scene_bound:

  min: [-2.0, -2.0, -2.0]

  max: [2.0, 2.0, 2.0]

voxel_grid:

  voxel_size: 0.02

  uniform_lattice: true

radial_filter:

  enable: false

  nb_neighbors: 5

  radius: 0.01

robot_filter_radius: 0.125