scene_bound:

  min: [-0.10, -0.30, -0.20]

  max: [+0.90, +0.40, +0.70]

voxel_grid:

  voxel_size: 0.01

  uniform_lattice: true

radial_filter:

  enable: false

  nb_neighbors: 5

  radius: 0.01

robot_filter_radius: 0.05