stream:
  depth_profile:
    w: 848
    h: 480
    f: 30
  temporal_filter:
    enable: true
    alpha: 0.05
    delta: 100.0
    pctrl: 7

  spatial_filter:
    enable: true
    mag: 5.0
    alpha: 0.25
    delta: 50.0
    hfill: 4.0

sensors:
  0:
    nickname: 'alpha'
    serial_no: '032622070733'
    pose:
      position:
        x: 0.38  # Position in meters (x-axis)
        y: 0.0  # Position in meters (y-axis)
        z: 0.0  # Position in meters (z-axis)
      orientation:
        roll: -1.57  # Rotation around x-axis in radians
        pitch: 0.0  # Rotation around y-axis in radians
        yaw: 1.57  # Rotation around z-axis in radians
  1:
    nickname: 'beta'
    serial_no: '142122070272'
    pose:
      position:
        x: 0.0  # Position in meters (x-axis)
        y: 0.38  # Position in meters (y-axis)
        z: 0.0  # Position in meters (z-axis)
      orientation:
        roll: -1.57  # Rotation around x-axis in radians
        pitch: 0.0  # Rotation around y-axis in radians
        yaw: 3.14  # Rotation around z-axis in radians


